CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
	id INTEGER (10) AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR (250) NOT NULL,
	devoured BOOLEAN DEFAULT 0,
	date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
	PRIMARY KEY (id)
);